version: "3.8"
services:
    bot:
        build: .
        env_file:
            - .env
        restart: unless-stopped
    cache:
        image: "redis:7-alpine"
        restart: unless-stopped
        volumes:
            - cache:/data

volumes:
    cache:
