version: "3.8"
services:
    bot:
        build: 
            context: .
            args:
                CONFIGURATION: "${CONFIGURATION}"
        env_file:
            - .env
        volumes:
            - ./appsettings.Development.json:/app/appsettings.Development.json
        depends_on: 
            - cache
            - database
        restart: unless-stopped
        
    database:
        image: mariadb:10.7
        env_file:
            - .env
        restart: unless-stopped
        
    cache:
        image: "redis:6-alpine"
        restart: unless-stopped
