version: "3.8"
services:
    bot:
        build: 
            context: .
            args:
                CONFIGURATION: "${CONFIGURATION}"
        env_file:
            - .env
        volumes:
            - ./appsettings.json:/app/appsettings.json
            - ./appsettings.Development.json:/app/appsettings.Development.json
        restart: unless-stopped
    cache:
        image: "redis:6-alpine"
        restart: unless-stopped
        volumes:
            - cache:/data

volumes:
    cache:
